name: CD
on:
  - push
  - pull_request

jobs:
  
      
  macosx:
    name: Mac OS X
    runs-on: macos-10.15
    if: True

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    

    - name: Package
      id: package
      run: |
        brew install --formula --build-bottle "formula/poppler-qt6.rb"
        brew bottle poppler-qt6
        ls -l
      

        
 
